variables:
  MATLAB_VERSION: R2022b
  OLD_MATLAB_VERSION: R2014a
  OCTAVE_VERSION: 7.3.0

before_script:
  - git clone https://git.dynare.org/Dynare/dseries.git

test_matlab:
  stage: test
  script:
    - make check-matlab MATLAB=/usr/local/MATLAB/$MATLAB_VERSION/bin/matlab
  artifacts:
    paths:
      - test/my/report/dir/report.pdf

test_old_matlab:
  stage: test
  script:
    - make check-matlab MATLAB=/usr/local/MATLAB/$OLD_MATLAB_VERSION/bin/matlab
  artifacts:
    paths:
      - test/my/report/dir/report.pdf

test_octave:
  stage: test
  script:
    - make check-octave OCTAVE=/usr/local/octave/$OCTAVE_VERSION/bin/octave
  artifacts:
    paths:
      - test/my/report/dir/report.pdf
